name: Linting (MyPy & Flake8)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          # Le cache permet d'accélérer l'exécution lors des prochains pushs
          cache: 'pip' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # On fige exactement la version que tu as en local
          pip install mypy==1.19.1 flake8
          
          # IMPORTANT : Installe tes dépendances projet pour que MyPy 
          # puisse analyser les types des bibliothèques externes (ex: Pydantic)
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run MyPy
        run: |
          mypy . --warn-return-any \
                 --warn-unused-ignores \
                 --ignore-missing-imports \
                 --disallow-untyped-defs \
                 --check-untyped-defs

      - name: Run Flake8
        run: |
          flake8 .
